name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Backend setup (Python)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Match the version used in your local environment

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        pytest backend/tests
      env:
        PYTHONPATH: ./backend  # Makes sure Python can find your backend modules

    # Ensure FastAPI can start (even if skeleton)
    - name: Start FastAPI Application (Testing API skeleton)
      run: |
        uvicorn backend.main:app --host 127.0.0.1 --port 8000 --reload &
        sleep 10
        curl http://127.0.0.1:8000

    # Frontend setup (Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Or the version you are using

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run ESLint
      run: |
        cd frontend
        npm run lint

    - name: Run frontend tests
      run: |
        cd frontend
        npm test
