name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/add-basic-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Ensure this matches your local environment

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        pytest backend/tests
      env:
        PYTHONPATH: ./backend  # This makes sure Python can find your backend module

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Or the version you are using

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run ESLint
      run: |
        cd frontend
        npm run lint

    - name: Run frontend tests
      run: |
        cd frontend
        npm test
